"""initial schema

Revision ID: 996e4dceab29
Revises:
Create Date: 2026-07-30 14:35:49.307812

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "996e4dceab29"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column(
            "book_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=160), nullable=False),
        sa.Column("publisher", sa.String(length=160), nullable=True),
        sa.Column("isbn", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("published_year", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "published_year BETWEEN 1400 AND 2100", name="book_published_year_check"
        ),
        sa.PrimaryKeyConstraint("book_id"),
        sa.UniqueConstraint("isbn"),
    )
    op.create_index("idx_book_isbn", "book", ["isbn"], unique=False)
    op.create_index("idx_book_title", "book", ["title"], unique=False)
    op.create_table(
        "member",
        sa.Column(
            "member_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=160), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("government_id_type", sa.String(length=40), nullable=True),
        sa.Column("government_id_number", sa.String(length=64), nullable=True),
        sa.Column("street", sa.String(length=160), nullable=True),
        sa.Column("city", sa.String(length=80), nullable=True),
        sa.Column("state", sa.String(length=80), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column(
            "membership_status",
            postgresql.ENUM("ACTIVE", "BLOCKED", "INACTIVE", name="membership_status"),
            server_default=sa.text("'ACTIVE'"),
            nullable=False,
        ),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("member_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("government_id_type", "government_id_number", name="uq_member_gov_id"),
    )
    op.create_index("idx_member_email", "member", ["email"], unique=False)
    op.create_index("idx_member_status", "member", ["membership_status"], unique=False)
    op.create_table(
        "staff",
        sa.Column(
            "staff_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("employee_code", sa.String(length=32), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=160), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("ADMIN", "LIBRARIAN", name="staff_role"),
            server_default=sa.text("'LIBRARIAN'"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("ACTIVE", "INACTIVE", name="staff_status"),
            server_default=sa.text("'ACTIVE'"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("staff_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("employee_code"),
    )
    op.create_index("idx_staff_email", "staff", ["email"], unique=False)
    op.create_index("idx_staff_employee_code", "staff", ["employee_code"], unique=False)
    op.create_table(
        "book_copy",
        sa.Column(
            "copy_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("barcode", sa.String(length=64), nullable=False),
        sa.Column("shelf_code", sa.String(length=32), nullable=True),
        sa.Column(
            "condition",
            postgresql.ENUM("NEW", "GOOD", "FAIR", "DAMAGED", name="copy_condition"),
            server_default=sa.text("'NEW'"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("AVAILABLE", "BORROWED", "LOST", "MAINTENANCE", name="copy_status"),
            server_default=sa.text("'AVAILABLE'"),
            nullable=False,
        ),
        sa.Column(
            "max_borrow_days", sa.SmallInteger(), server_default=sa.text("14"), nullable=False
        ),
        sa.Column(
            "late_fee_per_day",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("5.00"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("late_fee_per_day >= 0", name="book_copy_late_fee_per_day_check"),
        sa.CheckConstraint("max_borrow_days > 0", name="book_copy_max_borrow_days_check"),
        sa.ForeignKeyConstraint(["book_id"], ["book.book_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("copy_id"),
        sa.UniqueConstraint("barcode"),
    )
    op.create_index("idx_copy_barcode", "book_copy", ["barcode"], unique=False)
    op.create_index("idx_copy_book_id", "book_copy", ["book_id"], unique=False)
    op.create_index("idx_copy_status", "book_copy", ["status"], unique=False)
    op.create_table(
        "loan",
        sa.Column(
            "loan_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("copy_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("issued_by_staff_id", sa.UUID(), nullable=False),
        sa.Column("received_by_staff_id", sa.UUID(), nullable=True),
        sa.Column(
            "borrowed_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("due_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("returned_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "borrow_condition",
            postgresql.ENUM("NEW", "GOOD", "FAIR", "DAMAGED", name="copy_condition"),
            nullable=False,
        ),
        sa.Column(
            "return_condition",
            postgresql.ENUM("NEW", "GOOD", "FAIR", "DAMAGED", name="copy_condition"),
            nullable=True,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("ACTIVE", "RETURNED", name="loan_status"),
            server_default=sa.text("'ACTIVE'"),
            nullable=False,
        ),
        sa.Column(
            "calculated_fine",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'ACTIVE' AND returned_at IS NULL) OR "
            "(status = 'RETURNED' AND returned_at IS NOT NULL)",
            name="chk_loan_returned_state",
        ),
        sa.CheckConstraint("calculated_fine >= 0", name="loan_calculated_fine_check"),
        sa.CheckConstraint("due_at > borrowed_at", name="chk_loan_due_after_borrow"),
        sa.ForeignKeyConstraint(["copy_id"], ["book_copy.copy_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["issued_by_staff_id"], ["staff.staff_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["member_id"], ["member.member_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["received_by_staff_id"], ["staff.staff_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("loan_id"),
    )
    op.create_index("idx_loan_copy_id", "loan", ["copy_id"], unique=False)
    op.create_index("idx_loan_due_at", "loan", ["due_at"], unique=False)
    op.create_index("idx_loan_member_id", "loan", ["member_id"], unique=False)
    op.create_index("idx_loan_status", "loan", ["status"], unique=False)
    op.create_index("idx_loan_status_due_at", "loan", ["status", "due_at"], unique=False)
    op.create_index(
        "one_active_loan_per_copy",
        "loan",
        ["copy_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "transaction",
        sa.Column(
            "transaction_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("loan_id", sa.UUID(), nullable=True),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column(
            "transaction_type",
            postgresql.ENUM("LATE_FEE", "DAMAGE_FEE", "WAIVER", name="transaction_type"),
            nullable=False,
        ),
        sa.Column(
            "payment_mode",
            postgresql.ENUM("CASH", "CARD", "UPI", "ONLINE", name="payment_mode"),
            nullable=True,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("payment_reference", sa.String(length=80), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "SUCCESS", "FAILED", "WAIVED", name="transaction_status"),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(transaction_type = 'WAIVER' AND payment_mode IS NULL) OR "
            "(transaction_type <> 'WAIVER')",
            name="chk_txn_waiver_mode",
        ),
        sa.CheckConstraint("amount >= 0", name="transaction_amount_check"),
        sa.ForeignKeyConstraint(["loan_id"], ["loan.loan_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["member_id"], ["member.member_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_index("idx_txn_created_at", "transaction", ["created_at"], unique=False)
    op.create_index("idx_txn_loan_id", "transaction", ["loan_id"], unique=False)
    op.create_index("idx_txn_member_id", "transaction", ["member_id"], unique=False)
    op.create_index("idx_txn_status", "transaction", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_txn_status", table_name="transaction")
    op.drop_index("idx_txn_member_id", table_name="transaction")
    op.drop_index("idx_txn_loan_id", table_name="transaction")
    op.drop_index("idx_txn_created_at", table_name="transaction")
    op.drop_table("transaction")
    op.drop_index(
        "one_active_loan_per_copy", table_name="loan", postgresql_where=sa.text("status = 'ACTIVE'")
    )
    op.drop_index("idx_loan_status_due_at", table_name="loan")
    op.drop_index("idx_loan_status", table_name="loan")
    op.drop_index("idx_loan_member_id", table_name="loan")
    op.drop_index("idx_loan_due_at", table_name="loan")
    op.drop_index("idx_loan_copy_id", table_name="loan")
    op.drop_table("loan")
    op.drop_index("idx_copy_status", table_name="book_copy")
    op.drop_index("idx_copy_book_id", table_name="book_copy")
    op.drop_index("idx_copy_barcode", table_name="book_copy")
    op.drop_table("book_copy")
    op.drop_index("idx_staff_employee_code", table_name="staff")
    op.drop_index("idx_staff_email", table_name="staff")
    op.drop_table("staff")
    op.drop_index("idx_member_status", table_name="member")
    op.drop_index("idx_member_email", table_name="member")
    op.drop_table("member")
    op.drop_index("idx_book_title", table_name="book")
    op.drop_index("idx_book_isbn", table_name="book")
    op.drop_table("book")
    # ### end Alembic commands ###
    # Autogenerate's drop_table calls leave the 9 backing Postgres ENUM types behind
    # (verified against a scratch DB), so they're dropped explicitly here, after every
    # column referencing them is gone.
    bind = op.get_bind()
    postgresql.ENUM(name="transaction_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="transaction_type").drop(bind, checkfirst=True)
    postgresql.ENUM(name="payment_mode").drop(bind, checkfirst=True)
    postgresql.ENUM(name="loan_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="copy_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="copy_condition").drop(bind, checkfirst=True)
    postgresql.ENUM(name="membership_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="staff_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="staff_role").drop(bind, checkfirst=True)
